/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();

// Precaches all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// ─── DEDUPLICATION CACHE ────────────────────────────────────────────────
// Prevents the same alarm from firing multiple times within the same
// minute window (the foreground scheduler runs every 60s but can overlap).
const recentlyFired = new Map<string, number>();

function shouldFire(tag: string): boolean {
  const now = Date.now();
  const lastFired = recentlyFired.get(tag);
  if (lastFired && now - lastFired < 55_000) return false; // 55-second window
  recentlyFired.set(tag, now);
  // Garbage-collect old entries to prevent memory leak
  if (recentlyFired.size > 200) {
    const cutoff = now - 120_000;
    for (const [key, ts] of recentlyFired) {
      if (ts < cutoff) recentlyFired.delete(key);
    }
  }
  return true;
}

// ─── MESSAGE HANDLER (from foreground scheduler) ────────────────────────
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SHOW_NOTIFICATION') {
    const { title, body, icon, badge, vibrate, tag, data } = event.data.payload;
    const finalTag = tag || 'seidaly-alert';

    if (!shouldFire(finalTag)) return;

    event.waitUntil(
      self.registration.showNotification(title, {
        body,
        icon: icon || '/pwa-192x192.png',
        badge: badge || '/pwa-192x192.png',
        vibrate: vibrate || [200, 100, 200],
        tag: finalTag,
        data: data || '/',
        actions: [
          { action: 'action-taken', title: '✅ تم أخذ الجرعة' },
          { action: 'action-remind', title: '⏰ تذكير بعد 15 دقيقة' }
        ],
        dir: 'rtl',
        lang: 'ar',
        renotify: true,
      } as any)
    );
  }
});

// ─── PUSH EVENT HANDLER (server-side push) ──────────────────────────────
self.addEventListener('push', (event: PushEvent) => {
  let data: any = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { body: event.data.text() };
    }
  }

  const title = data.title || 'Seidaly - صيدلي ⏰';
  const options: any = {
    body: data.body || 'لديك إشعار جديد بخصوص أدويتك.',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [200, 100, 200],
    tag: data.tag || 'seidaly-push',
    data: data.url || '/',
    dir: 'rtl',
    lang: 'ar',
    renotify: true,
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// ─── PERIODIC BACKGROUND SYNC (for when the app is closed) ─────────────
self.addEventListener('periodicsync' as any, (event: any) => {
  if (event.tag === 'medication-alarm-sync') {
    event.waitUntil(checkBackgroundAlarms());
  }
});

// Also handle regular background sync as a fallback
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'medication-alarm-sync') {
    event.waitUntil(checkBackgroundAlarms());
  }
});

/**
 * Reads medication data from IndexedDB-based localStorage workaround
 * (Service workers can't access localStorage directly, so we use
 * the Cache API as a bridge for the alarm data).
 * 
 * Alternatively, the foreground app writes the alarms data to the
 * cache before being suspended — see App.tsx scheduler.
 */
async function checkBackgroundAlarms(): Promise<void> {
  try {
    const cache = await caches.open('seidaly-alarm-data');
    const response = await cache.match('/alarm-data.json');
    if (!response) return;

    const data = await response.json();
    const membersData = data.membersData || {};
    const familyList = data.familyMembers || [];

    const now = new Date();
    let hours = now.getHours();
    const minutes = now.getMinutes();
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12;
    hours = hours ? hours : 12;
    const strHours = hours < 10 ? '0' + hours : hours.toString();
    const strMinutes = minutes < 10 ? '0' + minutes : minutes.toString();
    const currentTimeStr = `${strHours}:${strMinutes} ${ampm}`;

    for (const memberId of Object.keys(membersData)) {
      const memberObj = membersData[memberId];
      const meds = memberObj.medications || [];
      const memberProfile = familyList.find((f: any) => f.id === memberId);
      const memberName = memberProfile
        ? memberProfile.name
        : memberId === 'me'
          ? 'الأساسي'
          : 'المرافق';

      for (const med of meds) {
        const timings = med.timings || [];
        if (timings.includes(currentTimeStr)) {
          const notificationTag = `alarm-bg-${med.id}-${currentTimeStr}`;
          if (!shouldFire(notificationTag)) continue;

          await self.registration.showNotification(
            `تذكير بموعد الدواء ⏰ (${med.name})`,
            {
              body: `حان الآن موعد جرعة ${med.name} (${med.dosage}) للمريض: ${memberName}. يرجى تناولها بالوقت المحدد.`,
              icon: '/pwa-192x192.png',
              badge: '/pwa-192x192.png',
              vibrate: [200, 100, 200],
              tag: notificationTag,
              data: {
                url: '/',
                medId: med.id,
                time: currentTimeStr
              },
              actions: [
                { action: 'action-taken', title: '✅ تم أخذ الجرعة' },
                { action: 'action-remind', title: '⏰ تذكير بعد 15 دقيقة' }
              ],
              dir: 'rtl',
              lang: 'ar',
              renotify: true,
            } as any
          );
        }
      }
    }
  } catch (err) {
    console.error('[Seidaly SW] Background alarm check failed:', err);
  }
}

// ─── NOTIFICATION CLICK HANDLER ─────────────────────────────────────────
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();

  const action = event.action;
  const notifData = event.notification.data || {};
  const medId = typeof notifData === 'object' ? notifData.medId : undefined;
  const time = typeof notifData === 'object' ? notifData.time : undefined;

  if (action === 'action-taken' && medId && time) {
    event.waitUntil(
      (async () => {
        try {
          const cache = await caches.open('seidaly-alarm-data');
          const response = await cache.match('/alarm-data.json');
          if (response) {
            const data = await response.json();
            const membersData = data.membersData || {};
            
            let found = false;
            for (const memberId of Object.keys(membersData)) {
              const memberObj = membersData[memberId];
              const meds = memberObj.medications || [];
              if (meds.some((m: any) => m.id === medId)) {
                if (!memberObj.takenSlots) memberObj.takenSlots = {};
                memberObj.takenSlots[`${medId}-${time}`] = true;
                found = true;
                break;
              }
            }

            if (found) {
              await cache.put(
                '/alarm-data.json',
                new Response(JSON.stringify(data), { headers: { 'Content-Type': 'application/json' } })
              );

              // Broadcast changes
              const windowClients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
              windowClients.forEach(client => {
                client.postMessage({
                  type: 'TAKEN_SLOT_UPDATED',
                  payload: { medId, time }
                });
              });
            }
          }
        } catch (err) {
          console.error('[Seidaly SW] Error in action-taken handler:', err);
        }
      })()
    );
  } else if (action === 'action-remind' && medId && time) {
    event.waitUntil(
      (async () => {
        try {
          const windowClients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
          windowClients.forEach(client => {
            client.postMessage({
              type: 'REMIND_LATER',
              payload: { medId, time, delayMinutes: 15 }
            });
          });
        } catch (err) {
          console.error('[Seidaly SW] Error in action-remind handler:', err);
        }
      })()
    );
  } else {
    // Default open window logic
    event.waitUntil(
      self.clients
        .matchAll({ type: 'window', includeUncontrolled: true })
        .then((windowClients) => {
          const targetPath = typeof notifData === 'object' ? (notifData.url || '/') : (notifData || '/');
          for (let i = 0; i < windowClients.length; i++) {
            const client = windowClients[i];
            const clientUrl = new URL(client.url, self.location.href).pathname;
            const targetUrl = new URL(targetPath, self.location.href).pathname;
            if (clientUrl === targetUrl && 'focus' in client) {
              return client.focus();
            }
          }
          if (self.clients.openWindow) {
            return self.clients.openWindow(targetPath);
          }
        })
    );
  }
});
