/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();

// Precaches all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen to message events from the frontend (e.g., local alarm triggers)
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SHOW_NOTIFICATION') {
    const { title, body, icon, badge, vibrate, tag, data } = event.data.payload;
    
    event.waitUntil(
      self.registration.showNotification(title, {
        body,
        icon: icon || '/pwa-192x192.png',
        badge: badge || '/pwa-192x192.png',
        vibrate: vibrate || [200, 100, 200],
        tag: tag || 'seidaly-alert',
        data: data || '/'
      } as any)
    );
  }
});

// Custom push notification handler
self.addEventListener('push', (event: PushEvent) => {
  let data: any = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { body: event.data.text() };
    }
  }
  
  const title = data.title || 'Seidaly - صيدلي ⏰';
  const options: any = {
    body: data.body || 'لديك إشعار جديد بخصوص أدويتك.',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [200, 100, 200],
    data: data.url || '/'
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// Handle notification click to focus or open the app window
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        const clientUrl = new URL(client.url, self.location.href).pathname;
        const targetUrl = new URL(event.notification.data || '/', self.location.href).pathname;
        if (clientUrl === targetUrl && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(event.notification.data || '/');
      }
    })
  );
});
